# SPDX-FileCopyrightText: Copyright (c) 2025-2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
EAD Formatter Tool — renders EAD cues and chapters into standard output files.

Produces three file types from the pipeline outputs:

1. WebVTT Description file (.vtt)
   Kind: descriptions — consumed by HTML <track kind="descriptions"> elements.
   Each EAD cue maps to one VTT cue with its timestamp range and description.

2. WebVTT Chapters file (.chapters.vtt)
   Kind: chapters — consumed by HTML <track kind="chapters"> elements.
   Enables chapter-level navigation in supporting video players.

3. TTML / DFXP file (.ttml)
   W3C Timed Text Markup Language — used in broadcast and streaming pipelines
   (SMPTE-TT, EBU-TT-D, Amazon IVS, etc.).

All three are returned as strings inside a JSON envelope so the agent can
store or present them without additional tool calls.

Output envelope:
  {
    "webvtt_descriptions": "WEBVTT\nKind: descriptions\n...",
    "webvtt_chapters": "WEBVTT\nKind: chapters\n...",
    "ttml": "<?xml version='1.0'...>",
    "webvtt_descriptions_filename": "video_id.ead.vtt",
    "webvtt_chapters_filename": "video_id.chapters.vtt",
    "ttml_filename": "video_id.ead.ttml",
    "cue_count": 42,
    "chapter_count": 5
  }
"""


import json
import logging
import re
from collections.abc import AsyncGenerator
from typing import Literal
from xml.sax.saxutils import escape as xml_escape

from nat.builder.builder import Builder
from nat.builder.framework_enum import LLMFrameworkEnum
from nat.builder.function_info import FunctionInfo
from nat.cli.register_workflow import register_function
from nat.data_models.function import FunctionBaseConfig
from pydantic import BaseModel
from pydantic import Field

from vss_agents.data_models.ead import Chapter
from vss_agents.data_models.ead import EADCue
from vss_agents.data_models.ead import seconds_to_ttml_timestamp
from vss_agents.data_models.ead import seconds_to_vtt_timestamp

logger = logging.getLogger(__name__)

_SAFE_FILENAME = re.compile(r"[^\w\-.]")


def _safe_filename(name: str) -> str:
    """Sanitise a string for use as a filename stem."""
    return _SAFE_FILENAME.sub("_", name).strip("_")[:80]


# ---------------------------------------------------------------------------
# WebVTT generation
# ---------------------------------------------------------------------------


def _build_webvtt_descriptions(cues: list[EADCue], video_title: str) -> str:
    """Build a WebVTT file with Kind: descriptions."""
    lines = [
        "WEBVTT",
        "Kind: descriptions",
        "Language: en",
        f"NOTE Generated by EAD Agent — {video_title}",
        "",
    ]
    output_index = 1
    for cue in cues:
        # Skip segments the VLM flagged as needing no description
        if not cue.description.strip():
            continue
        start = seconds_to_vtt_timestamp(cue.start_seconds)
        end = seconds_to_vtt_timestamp(cue.end_seconds)
        lines.append(str(output_index))
        lines.append(f"{start} --> {end}")
        lines.append(cue.description)
        lines.append("")
        output_index += 1
    return "\n".join(lines)


def _build_webvtt_chapters(chapters: list[Chapter]) -> str:
    """Build a WebVTT file with Kind: chapters."""
    lines = [
        "WEBVTT",
        "Kind: chapters",
        "",
    ]
    for ch in chapters:
        start = seconds_to_vtt_timestamp(ch.start_seconds)
        end = seconds_to_vtt_timestamp(ch.end_seconds)
        lines.append(f"{ch.index + 1}")
        lines.append(f"{start} --> {end}")
        lines.append(ch.title)
        lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# TTML generation
# ---------------------------------------------------------------------------


def _build_ttml(cues: list[EADCue], video_title: str) -> str:
    """Build a TTML (W3C Timed Text Markup Language) Extended Audio Description file."""
    cue_elements = []
    for cue in cues:
        # Skip segments the VLM flagged as needing no description
        if not cue.description.strip():
            continue
        start = seconds_to_ttml_timestamp(cue.start_seconds)
        end = seconds_to_ttml_timestamp(cue.end_seconds)
        safe_desc = xml_escape(cue.description)
        cue_elements.append(
            f'      <p xml:id="cue{cue.index}" begin="{start}" end="{end}" '
            f'region="r1" style="s1">{safe_desc}</p>'
        )

    cues_block = "\n".join(cue_elements)
    safe_title = xml_escape(video_title)

    return f"""<?xml version="1.0" encoding="UTF-8"?>
<tt xml:lang="en"
    xmlns="http://www.w3.org/ns/ttml"
    xmlns:tts="http://www.w3.org/ns/ttml#styling"
    xmlns:ttm="http://www.w3.org/ns/ttml#metadata"
    xmlns:ttp="http://www.w3.org/ns/ttml#parameter"
    ttp:profile="http://www.w3.org/ns/ttml/profile/dfxp-presentation">
  <head>
    <metadata>
      <ttm:title>{safe_title} — Extended Audio Description</ttm:title>
      <ttm:desc>Extended Audio Description generated by EAD Agent</ttm:desc>
      <ttm:copyright>Extended audio descriptions are accessibility output</ttm:copyright>
    </metadata>
    <styling>
      <style xml:id="s1"
             tts:fontFamily="proportionalSansSerif"
             tts:fontSize="100%"
             tts:color="white"
             tts:backgroundColor="transparent"
             tts:textAlign="center"/>
    </styling>
    <layout>
      <region xml:id="r1"
              tts:displayAlign="after"
              tts:textAlign="center"
              tts:extent="90% 40%"
              tts:origin="5% 55%"/>
    </layout>
  </head>
  <body>
    <div>
{cues_block}
    </div>
  </body>
</tt>"""


# ---------------------------------------------------------------------------
# NAT tool registration
# ---------------------------------------------------------------------------


class EADFormatterConfig(FunctionBaseConfig, name="ead_formatter"):
    """Configuration for the EAD Formatter tool."""

    model_config = {"extra": "forbid"}


class EADFormatterInput(BaseModel):
    """Input for the EAD Formatter tool."""

    ead_cues_json: str = Field(
        ...,
        description="JSON array of EADCue objects — the output of visual_describer.",
    )
    chapters_json: str = Field(
        default="[]",
        description=(
            "JSON array of Chapter objects — the output of chapter_generator. "
            "Pass an empty array '[]' to skip chapter file generation."
        ),
    )
    video_title: str | None = Field(
        default=None,
        description="Video title used in file headers and filename stems. Defaults to 'video'.",
    )
    output_format: Literal["webvtt"] = Field(
        default="webvtt",
        description="Output format. Only WebVTT is supported.",
    )

    model_config = {"extra": "forbid"}


@register_function(config_type=EADFormatterConfig, framework_wrappers=[LLMFrameworkEnum.LANGCHAIN])
async def ead_formatter(config: EADFormatterConfig, builder: Builder) -> AsyncGenerator[FunctionInfo]:
    """EAD Formatter — renders EAD cues and chapters into WebVTT and TTML files."""

    async def _ead_formatter(input: EADFormatterInput) -> str:
        """
        Render Extended Audio Description cues and chapters into WebVTT caption files.

        Produces two files:
        • WebVTT descriptions (.ead.vtt)    — use with <track kind="descriptions">
        • WebVTT chapters (.chapters.vtt)   — use with <track kind="chapters">

        Returns:
            JSON object containing file contents and suggested filenames:
              webvtt_descriptions, webvtt_chapters  (content strings)
              webvtt_descriptions_filename, webvtt_chapters_filename
              cue_count, skipped_cue_count, chapter_count
        """
        # Parse cues
        try:
            raw_cues = json.loads(input.ead_cues_json)
            cues = [EADCue.model_validate(c) for c in raw_cues]
        except Exception as e:
            raise ValueError(f"Failed to parse ead_cues_json: {e}") from e

        # Parse chapters
        try:
            raw_chapters = json.loads(input.chapters_json) if input.chapters_json.strip() else []
            chapters = [Chapter.model_validate(ch) for ch in raw_chapters]
        except Exception as e:
            logger.warning(f"Failed to parse chapters_json — skipping chapters: {e}")
            chapters = []

        title = input.video_title or "video"
        stem = _safe_filename(title)
        fmt = input.output_format

        logger.info(
            f"Formatting {len(cues)} EAD cues + {len(chapters)} chapters "
            f"as '{fmt}' for '{title}'"
        )

        described_cues = [c for c in cues if c.description.strip()]
        result: dict = {
            "cue_count": len(described_cues),
            "skipped_cue_count": len(cues) - len(described_cues),
            "chapter_count": len(chapters),
            "webvtt_descriptions": _build_webvtt_descriptions(cues, title),
            "webvtt_descriptions_filename": f"{stem}.ead.vtt",
            "webvtt_chapters": _build_webvtt_chapters(chapters) if chapters else None,
            "webvtt_chapters_filename": f"{stem}.chapters.vtt",
        }

        return json.dumps(result, indent=2, ensure_ascii=False)

    yield FunctionInfo.create(
        single_fn=_ead_formatter,
        description=_ead_formatter.__doc__,
        input_schema=EADFormatterInput,
        single_output_schema=str,
    )
